FROM quay.io/jupyter/minimal-notebook

USER root

COPY --chown=${NB_UID}:${NB_GID} requirements.txt /tmp/

RUN pip install --no-cache-dir --requirement /tmp/requirements.txt && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

RUN apt-get update --yes && \
    apt-get install --yes --no-install-recommends \
    libpq-dev \
    libgdal-dev \
    libudunits2-dev \
    libfontconfig1-dev \
    libgit2-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    r-base \
    gfortran \
    gcc \
    build-essential && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN R -e 'install.packages(c("IRkernel", "remotes", "devtools", "tidyverse", "sf", "terra", "arrow", "ggplot2", "worrms", "leaflet", "seqinr", "BiocManager", "robis"), repos = "http://cran.us.r-project.org")'
RUN R -e 'remotes::install_github("iobis/obistools")'
RUN R -e 'remotes::install_github("pieterprovoost/r-dwca-writer")'
RUN R -e 'BiocManager::install(c("phyloseq", "Biostrings"))'

RUN ln -s /home/jovyan/shared /home/jovyan/work/shared
RUN ln -s /home/jovyan/data /home/jovyan/work/data
RUN fix-permissions "/usr/local/lib/R/site-library"

USER ${NB_UID}

RUN R -e 'IRkernel::installspec()'
