FROM quay.io/jupyter/minimal-notebook:latest

USER root

COPY --chown=${NB_UID}:${NB_GID} requirements.txt /tmp/

RUN pip install --no-cache-dir --requirement /tmp/requirements.txt && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

RUN apt-get update --yes && \
    apt-get install --yes --no-install-recommends \
    libpq-dev \
    libgdal-dev \
    libudunits2-dev \
    libfontconfig1-dev \
    libgit2-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    r-base \
    gfortran \
    gcc \
    vim \
    build-essential && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/marbl/Krona/archive/refs/tags/v2.8.1.tar.gz && \
    tar -xvzf v2.8.1.tar.gz && \
    cd Krona-2.8.1/KronaTools/ && \
    ./install.pl && \
    rm ../../v2.8.1.tar.gz

RUN R -e 'install.packages(c("IRkernel", "remotes", "devtools", "tidyverse", "sf", "terra", "arrow", "ggplot2", "worrms", "leaflet", "seqinr", "BiocManager", "robis"), repos = "http://cran.us.r-project.org"); BiocManager::install(c("phyloseq", "Biostrings")); library(remotes); install_github("iobis/obistools"); install_github("pieterprovoost/r-dwca-writer"); install_github("cpauvert/psadd")'

RUN ln -s /home/jovyan/shared /home/jovyan/work/shared
RUN ln -s /home/jovyan/data /home/jovyan/work/data
RUN ln -s /home/jovyan/scratch /home/jovyan/work/scratch
RUN fix-permissions "/usr/local/lib/R/site-library"

USER ${NB_UID}

RUN R -e 'IRkernel::installspec()'
